[project]
name = "06-01-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytelegrambotapi>=4.29.1",
    "telebotapi>=0.9.9.3",
]
